name: escalate
channels:
  - defaults
dependencies:
<<<<<<< HEAD
  - astroid=2.1.0=py36_0
  - blas=1.0=mkl
  - ca-certificates=2018.12.5=0
  - certifi=2018.11.29=py36_0
  - cycler=0.10.0=py36hfc81398_0
  - cython=0.29.2=py36h0a44026_0
  - freetype=2.9.1=hb4e5f40_0
  - intel-openmp=2019.1=144
  - isort=4.3.4=py36_0
  - kiwisolver=1.0.1=py36h0a44026_0
  - lazy-object-proxy=1.3.1=py36h1de35cc_2
=======
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py36_0
  - cycler=0.10.0=py36hfc81398_0
  - cython=0.29.4=py36h0a44026_0
  - freetype=2.9.1=hb4e5f40_0
  - intel-openmp=2019.1=144
  - kiwisolver=1.0.1=py36h0a44026_0
>>>>>>> master
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.36=ha441bb4_0
  - matplotlib=3.0.2=py36h54f8f79_0
<<<<<<< HEAD
  - mccabe=0.6.1=py36_1
=======
>>>>>>> master
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36h5e564d8_0
  - mkl_random=1.0.2=py36h27c97d8_0
  - ncurses=6.1=h0a44026_1
  - numpy=1.15.4=py36hacdab7b_0
  - numpy-base=1.15.4=py36h6575580_0
  - openssl=1.1.1a=h1de35cc_0
<<<<<<< HEAD
  - pandas=0.24.0=py36h0a44026_0
  - pip=18.1=py36_0
  - pylint=2.2.2=py36_0
=======
  - pandas=0.24.1=py36h0a44026_0
>>>>>>> master
  - pyparsing=2.3.1=py36_0
  - python=3.6.8=haf84260_0
  - python-dateutil=2.7.5=py36_0
  - pytz=2018.9=py36_0
  - readline=7.0=h1de35cc_5
<<<<<<< HEAD
  - setuptools=40.6.3=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.26.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - tornado=5.1.1=py36h1de35cc_0
  - typed-ast=1.1.0=py36h1de35cc_0
  - wheel=0.32.3=py36_0
  - wrapt=1.11.0=py36h1de35cc_0
=======
  - setuptools=40.7.3=py36_0
  - sqlite=3.26.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - tornado=5.1.1=py36h1de35cc_0
  - wheel=0.32.3=py36_0
>>>>>>> master
  - xlrd=1.2.0=py36_0
  - xlwt=1.2.0=py36h5ad1178_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
<<<<<<< HEAD
=======
  - pip:
    - astroid==2.0.2
    - cachetools==2.1.0
    - chardet==3.0.4
    - google-api-python-client==1.7.4
    - google-auth==1.5.0
    - google-auth-httplib2==0.0.3
    - gspread==3.0.1
    - httplib2==0.11.3
    - idna==2.7
    - isort==4.3.4
    - lazy-object-proxy==1.3.1
    - mccabe==0.6.1
    - oauth2client==4.1.2
    - optunity==1.1.1
    - pip==18.1
    - pyasn1==0.4.3
    - pyasn1-modules==0.2.2
    - pydrive==1.3.1
    - pylint==2.1.1
    - pyyaml==3.13
    - requests==2.19.1
    - rsa==3.4.2
    - six==1.11.0
    - typed-ast==1.1.0
    - typing==3.6.4
    - uritemplate==3.0.0
    - urllib3==1.23
    - wrapt==1.10.11
>>>>>>> master
prefix: /anaconda3/envs/escalate

